<a href="https://colab.research.google.com/github/malee4/summer22_researchproj/blob/master/ALS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.optimize import minimize

In [5]:
m = 2
n = 3
E = 0.01
# array = np.random.rand(m, n)
array = np.array([[2, 1, 1], [1, 0, 1]])
u = np.ones((m, 1))
p = np.ones((1, n))

print(array)
print(u)
print(p)
# print(array[0][0])

[[2 1 1]
 [1 0 1]]
[[1.]
 [1.]]
[[1. 1. 1.]]


In [6]:
# objective: argmin sum((aij - ui * pj)^2)

for k in range(100):
  x_index = 0
  y_index = 0

  for j in range(n):
    def row_loss_function(x):
      sum = 0
      for i in range(len(u)):
        sum += (array[i][x_index] - x * u[i][0])**2
      return sum
    p[0][j] = minimize(row_loss_function, x0 = 0.5).x
    x_index += 1

  # print(p)

  for i in range(m):
    def col_loss_function(y):
      sum = 0
      for j in range(len(p)):
        sum += (array[y_index][j] - y * p[0][j])**2
      return sum
    u[i][0] = minimize(col_loss_function, x0 = 0.5).x
    y_index += 1

  # print(u)

out = np.matmul(u, p)
print(out)
# print(u)
# print(p)
# alternating least squares
# initialize random values for u (col), p (row)
u = np.ones((m, 1))




[[1.99999999 0.8        1.2       ]
 [1.         0.4        0.6       ]]


Federated ALS Demo

In [ ]:
# for some number of iterations
  # run local ALS and average